/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_control_ ## ID
#endif

#include <math.h>
#include "casadi_mem.h"
// #include "f_control.h"

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

casadi_real casadi_sq(casadi_real x) { return x*x;}

/* f_control:(q[4],omega_b[3],v_n[3],u_cmd[4],iclimbr_err_old,gains[6],dt)->(u[4],i_climbr_err_new) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[5] ? arg[5][1] : 0;
  a1=9.9999999999999995e-08;
  a2=1.;
  a3=arg[0] ? arg[0][1] : 0;
  a4=arg[0] ? arg[0][0] : 0;
  a4=(a2+a4);
  a3=(a3/a4);
  a5=casadi_sq(a3);
  a6=arg[0] ? arg[0][2] : 0;
  a6=(a6/a4);
  a7=casadi_sq(a6);
  a5=(a5+a7);
  a7=arg[0] ? arg[0][3] : 0;
  a7=(a7/a4);
  a4=casadi_sq(a7);
  a5=(a5+a4);
  a5=sqrt(a5);
  a5=(a2<a5);
  a4=casadi_sq(a3);
  a8=casadi_sq(a6);
  a4=(a4+a8);
  a8=casadi_sq(a7);
  a4=(a4+a8);
  a8=(a3/a4);
  a8=(-a8);
  a8=(a5?a8:0);
  a9=(!a5);
  a3=(a9?a3:0);
  a8=(a8+a3);
  a3=casadi_sq(a8);
  a10=(a6/a4);
  a10=(-a10);
  a10=(a5?a10:0);
  a6=(a9?a6:0);
  a10=(a10+a6);
  a6=casadi_sq(a10);
  a3=(a3+a6);
  a4=(a7/a4);
  a4=(-a4);
  a5=(a5?a4:0);
  a9=(a9?a7:0);
  a5=(a5+a9);
  a9=casadi_sq(a5);
  a3=(a3+a9);
  a9=(a2-a3);
  a7=arg[3] ? arg[3][0] : 0;
  a4=2.;
  a6=(a7/a4);
  a6=sin(a6);
  a11=arg[3] ? arg[3][1] : 0;
  a12=(a11/a4);
  a12=cos(a12);
  a13=(a6*a12);
  a14=arg[3] ? arg[3][2] : 0;
  a15=(a14/a4);
  a15=cos(a15);
  a13=(a13*a15);
  a7=(a7/a4);
  a7=cos(a7);
  a11=(a11/a4);
  a11=sin(a11);
  a16=(a7*a11);
  a14=(a14/a4);
  a14=sin(a14);
  a16=(a16*a14);
  a13=(a13-a16);
  a16=(a7*a12);
  a16=(a16*a15);
  a17=(a6*a11);
  a17=(a17*a14);
  a16=(a16+a17);
  a16=(a2+a16);
  a13=(a13/a16);
  a17=casadi_sq(a13);
  a18=(a7*a11);
  a18=(a18*a15);
  a19=(a6*a12);
  a19=(a19*a14);
  a18=(a18+a19);
  a18=(a18/a16);
  a19=casadi_sq(a18);
  a17=(a17+a19);
  a7=(a7*a12);
  a7=(a7*a14);
  a6=(a6*a11);
  a6=(a6*a15);
  a7=(a7-a6);
  a7=(a7/a16);
  a16=casadi_sq(a7);
  a17=(a17+a16);
  a17=sqrt(a17);
  a17=(a2<a17);
  a16=casadi_sq(a13);
  a6=casadi_sq(a18);
  a16=(a16+a6);
  a6=casadi_sq(a7);
  a16=(a16+a6);
  a6=(a13/a16);
  a6=(-a6);
  a6=(a17?a6:0);
  a15=(!a17);
  a13=(a15?a13:0);
  a6=(a6+a13);
  a13=(a9*a6);
  a11=casadi_sq(a6);
  a14=(a18/a16);
  a14=(-a14);
  a14=(a17?a14:0);
  a18=(a15?a18:0);
  a14=(a14+a18);
  a18=casadi_sq(a14);
  a11=(a11+a18);
  a16=(a7/a16);
  a16=(-a16);
  a17=(a17?a16:0);
  a15=(a15?a7:0);
  a17=(a17+a15);
  a15=casadi_sq(a17);
  a11=(a11+a15);
  a15=(a2-a11);
  a7=(a15*a8);
  a13=(a13-a7);
  a7=(a5*a14);
  a16=(a10*a17);
  a7=(a7-a16);
  a7=(a4*a7);
  a13=(a13-a7);
  a11=(a11*a3);
  a11=(a2+a11);
  a3=(a8*a6);
  a7=(a10*a14);
  a3=(a3+a7);
  a7=(a5*a17);
  a3=(a3+a7);
  a3=(a4*a3);
  a11=(a11+a3);
  a13=(a13/a11);
  a3=casadi_sq(a13);
  a7=(a9*a14);
  a16=(a15*a10);
  a7=(a7-a16);
  a16=(a8*a17);
  a18=(a5*a6);
  a16=(a16-a18);
  a16=(a4*a16);
  a7=(a7-a16);
  a7=(a7/a11);
  a16=casadi_sq(a7);
  a3=(a3+a16);
  a9=(a9*a17);
  a15=(a15*a5);
  a9=(a9-a15);
  a10=(a10*a6);
  a8=(a8*a14);
  a10=(a10-a8);
  a10=(a4*a10);
  a9=(a9-a10);
  a9=(a9/a11);
  a11=casadi_sq(a9);
  a3=(a3+a11);
  a3=sqrt(a3);
  a1=(a1<a3);
  a11=4.;
  a10=atan(a3);
  a11=(a11*a10);
  a13=(a11*a13);
  a13=(a13/a3);
  a10=arg[5] ? arg[5][0] : 0;
  a13=(a13*a10);
  a13=(a1?a13:0);
  a8=arg[1] ? arg[1][0] : 0;
  a13=(a13-a8);
  a13=(a0*a13);
  if (res[0]!=0) res[0][0]=a13;
  a7=(a11*a7);
  a7=(a7/a3);
  a7=(a7*a10);
  a7=(a1?a7:0);
  a10=arg[1] ? arg[1][1] : 0;
  a7=(a7-a10);
  a0=(a0*a7);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[5] ? arg[5][3] : 0;
  a11=(a11*a9);
  a11=(a11/a3);
  a3=arg[5] ? arg[5][2] : 0;
  a11=(a11*a3);
  a1=(a1?a11:0);
  a11=arg[1] ? arg[1][2] : 0;
  a1=(a1-a11);
  a0=(a0*a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[5] ? arg[5][4] : 0;
  a1=arg[3] ? arg[3][3] : 0;
  a11=5.0000000000000000e-01;
  a1=(a1-a11);
  a4=(a4*a1);
  a1=arg[2] ? arg[2][2] : 0;
  a11=(a4+a1);
  a0=(a0*a11);
  a11=arg[5] ? arg[5][5] : 0;
  a3=arg[4] ? arg[4][0] : 0;
  a4=(a4+a1);
  a1=arg[6] ? arg[6][0] : 0;
  a4=(a4*a1);
  a3=(a3+a4);
  a11=(a11*a3);
  a0=(a0+a11);
  a11=0.;
  a11=(a0<a11);
  a11=(!a11);
  a4=(a2<a0);
  a2=(a4?a2:0);
  a4=(!a4);
  a4=(a4?a0:0);
  a2=(a2+a4);
  a11=(a11?a2:0);
  if (res[0]!=0) res[0][3]=a11;
  if (res[1]!=0) res[1][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_control(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void f_control_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_control_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_control_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int f_control_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* f_control_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "omega_b";
    case 2: return "v_n";
    case 3: return "u_cmd";
    case 4: return "iclimbr_err_old";
    case 5: return "gains";
    case 6: return "dt";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_control_name_out(casadi_int i){
  switch (i) {
    case 0: return "u";
    case 1: return "i_climbr_err_new";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_control_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    case 6: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_control_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_control_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* f_control_functions(void) {
  static casadi_functions fun = {
    f_control_incref,
    f_control_decref,
    f_control_n_in,
    f_control_n_out,
    f_control_name_in,
    f_control_name_out,
    f_control_sparsity_in,
    f_control_sparsity_out,
    f_control_work,
    f_control
  };
  return &fun;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
